version: "3"
services:
    frontend:
        container_name: awesome_web
        build:
            context: ./client
            dockerfile: Dockerfile
        image: fady/awesome_web
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        depends_on: 
            - mongodb
    backend:
        container_name: awesome_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: fady/awesome_server
        ports:
            - "3001:3001"
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
            
    mongodb:
        container_name: mongo
        image: mongo
        volumes:
                - ./data:/data/db
        ports:
            - 27017:27017